name: Publish to GitHub Pages

on:
  push:
    branches: 
      - main
      - webpage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: moralpain
          webRenderer: canvaskit
          baseHref: /moralpain_dev/
